APP1/urls.py
from django.urls import path, include

from . import views

app_name = 'APP1'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.news_search_result, name='search'),
]

corona_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from feedback.views import olah

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('APP1.urls')),
    path('forums/', include('forums.urls')),
    path('news/', include('news.urls')),
    path('userProfile/', include('userProfile.urls')),
    path('feedback/', include('feedback.urls')),
    path('rate/', olah, name = "olah"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
from django.urls import path

from . import views

app_name = 'feedback'

urlpatterns = [
    path('', views.home, name='feedback'),
    path('add/', views.home, name = 'add'),
]

forums/urls.py
from django.urls import path

from . import views

app_name = 'forums'

urlpatterns = [
    path('', views.forums, name='forums'),
    path('add_forum/', views.add_forum, name='forums_add_forum'),
    path('<int:pk>', views.detail_forum, name='forums_detail_forum'),
    path('delete_forum/<int:pk>', views.delete_forum, name='forums_delete_forum'),
]

news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news, name='news'),
    path('<int:news_id>/<str:news_title>/', views.news_detail, name='news_detail'),
]

userProfile/urls.py
from django.urls import path
from . import views

app_name = 'userProfile'

urlpatterns = [
	path('signup/',views.signup_view,name="signup"),
	path('logout/',views.logout_view,name="logout"),
	path('login/',views.login_view,name="login"),
	path('profile/',views.profile_view,name="profile"),
]

APP1/models.py
from django.db import models

# Create your models here.

APP1/views.py
from django.shortcuts import redirect, render
from news.models import News
from forums.models import Forum
from django.db.models import Q
from news.utils import retrieve_API
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from forum.models import Forum
# Create your views here.


def index(request):
    retrieve_API()
    request.session['forums_item'] = Forum.objects.all().count()
    request.session['news_item'] = News.objects.all().count()
    context = {
        'list_news': News.objects.all().order_by('-timestamp')[:3]
    }
    return render(request, 'APP1/landing.html', context)

def news_search_result(request):
    
    if request.method == "GET":
        keyword = request.GET.get('search')
        articles = News.objects\
            .filter(Q(title__icontains=keyword) | Q(content__icontains=keyword))\
            .order_by('-timestamp')
        paginator = Paginator(articles, 10)
        q_page = request.GET.get('page')
        page = int(q_page) if q_page != None else None

        try:
            articles = paginator.page(page)
        except PageNotAnInteger:
            articles = paginator.page(1)
        except EmptyPage:
            articles = paginator.page(paginator.num_pages)

        context = {
            'articles': articles,
            'page': page,
            'paginator': paginator,
            'key':keyword
        }
        return render(request, 'APP1/search_result.html', context)
    return redirect('APP1:index')

APP1/templates/APP1/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href={% static 'APP1/base.css' %}>
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'APP1/icon/icon.svg' %}"/>

  {% block head %}

  {% endblock head %}

  <title>CoronaTracker Lite</title>


</head>

<body>

  <section class="navbar">
    <nav>
      <div class="nav-wrapper nav__mod">
        <a href={% url 'APP1:index' %} class="brand-logo left"><img class="logo__app"
            src={% static 'APP1/icon/logo-app.svg' %} alt=""></a>
        <a href="#" style="transform: translateX(10px);" data-target="mobile-demo" class="sidenav-trigger right"><i
            class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down mid__ul">
          {% with url_name=request.resolver_match.url_name%}
          <li class="mid__ul__li {% if url_name == 'forums' %}under__line{% endif %}">
            <a class="li__mod tooltipped" data-position="bottom" data-tooltip="Forum" href={% url 'forums:forums' %}>
              <img class="icon__mod" src="
              {% if url_name == 'forums' %}
                {% static 'APP1/icon/forum_filled.svg' %}
              {% else %}
                {% static 'APP1/icon/forum.svg' %}
              {% endif %}
              " alt="">
              
            </a>
          </li>
          <li class="mid__ul__li {% if url_name == 'news' %}under__line{% endif %}">
            <a class="li__mod tooltipped" data-position="bottom" data-tooltip="News" href={% url 'news:news' %}>
              <img class="icon__mod" src="
              {% if url_name == 'news' %}
                {% static 'APP1/icon/news_filled.svg' %}
              {% else %}
                {% static 'APP1/icon/news.svg' %}
              {% endif %}
              " alt="">
            </a>
          </li>
          <li class="mid__ul__li {% if url_name == 'feedback' %}under__line{% endif %}">
            <a class="li__mod tooltipped" data-position="bottom" data-tooltip="Feedback" href={% url 'feedback:feedback' %}>
              <img class="icon__mod" src="
              {% if url_name == 'feedback' %}
                {% static 'APP1/icon/feedback_filled.svg' %}
              {% else %}
                {% static 'APP1/icon/feedback.svg' %}
              {% endif %}
              " alt="">
            </a>
          </li>
          
          {%endwith%}
          <li>
            <a class="li__mod dropdown-trigger" data-target='dropdown1'>
              

              {% if request.user.is_authenticated %}
                
                <img class="icon__mod icon__mod2 profile__img" src="{{request.user.account.image}}">
                {{ request.user.account.name | title | truncatechars:8}} <i class="material-icons">expand_more</i>

              {% else %}
              <img 
              class="icon__mod icon__mod2 profile__img" 
              src={% static 'APP1/icon/profile.svg' %} alt="">
              Profile <i class="material-icons">expand_more</i>
              {% endif %}

            </a>
          </li>

        </ul>
        <ul id='dropdown1' class='dropdown-content'>
          
          {% if request.user.is_authenticated %}
            <li><a href="{% url 'userProfile:profile' %}">Profile</a></li>
            <li class="divider" tabindex="-1"></li>
            <li><a href={% url 'userProfile:logout' %}>Logout</a></li>
          {% else %}
            <li><a href={% url 'userProfile:signup' %}>Sign Up</a></li>
            <li class="divider" tabindex="-1"></li>
            <li><a href={% url 'userProfile:login' %}>Login</a></li>
          {% endif %}

        </ul>
        <form class="form__search" action={% url 'APP1:search' %} method="GET">
          <button type="submit" class="icon__svg">
            <img src={% static 'APP1/icon/search.svg' %} alt="">
          </button>
          <input class="input__search" type="text" name="search" placeholder="Search News">
        </form>
      </div>
    </nav>

    <!-- INI SIDENAVNYA KLO MOBILE VIEW -->
    <ul class="sidenav right" id="mobile-demo">
      {% if request.user.is_authenticated %}
      
      <li>
        
          <div class="user-view">
            
            <div class="background" style="background: linear-gradient(179.01deg, #832161 0.82%, #DA4167 99.15%);">
              <!-- <img src="https://p4.wallpaperbetter.com/wallpaper/922/821/102/purple-is-my-color-wallpaper-preview.jpg"> -->
            </div>
            <div style="display: flex; justify-content: left; align-items: center; margin-bottom: 5px;">
              
              <img class="icon__mod icon__mod2 profile__img" src="{{request.user.account.image}}">
              
              <a style="flex: .9;">
                <span style="margin: 0;font-size: 1.5rem;"
                  class="white-text name">{{ request.user.account.name | title | truncatechars:8 }}</span>
              </a>
              <a class="link__profile" href="{% url 'userProfile:profile' %}">
                <i class="small material-icons">edit</i>edit
              </a>
            </div>
            <a style="padding: 5px 0;" class="link__profile">
              <i class="tiny material-icons">work</i>
              <span style="padding: 0 5px;" class="white-text email">
                {{ request.user.account.job | default:"Job" }}, 
                {{ request.user.account.age }}th
              </span>
            </a>
            <a style="padding: 5px 0 10px;" class="link__profile">
              <i class="tiny material-icons">email</i>
              <span style="padding: 0 5px;" class="white-text email">{{ request.user.account.email | default:"Email" }}</span>
            </a>
          </div>
      </li>
      {% endif %}

      <li>
        <div class="time relative">
          <i class="small material-icons">access_time</i>
          <span class="clock"></span>
        </div>
      </li>
      <li>
        <a style="display: flex;" href={% url 'forums:forums' %}>
          <img class="icon__mod icon__mod2" src={% static 'APP1/icon/forum.svg' %} alt="">
          Forums
          <span class="new badge new__badge">{{ request.session.forums_item }}</span>
        </a>
      </li>
      <li>
        <a style="display: flex;" href={% url 'news:news' %}>
          <img class="icon__mod icon__mod2" src={% static 'APP1/icon/news.svg' %} alt="">
          News
          <span class="new badge new__badge">{{ request.session.news_item }}</span>
        </a>
      </li>
      <li>
        <a style="display: flex;" href={% url 'feedback:feedback' %}>
          <img class="icon__mod icon__mod2" src={% static 'APP1/icon/feedback.svg' %} alt="">
          Feedback
        </a>
      </li>
      <li class="divider" tabindex="-1"></li>
      {% if request.user.is_authenticated %}
        <li>
          <a style="display: flex;" data-target='dropdown2' href={% url 'userProfile:logout' %}>
            <img class="icon__mod icon__mod2" src={% static 'APP1/icon/logout.svg' %} alt="">
            Logout
          </a>
        </li>
      {% else %}
      
        <li>
          <a style="display: flex;" data-target='dropdown2' href={% url 'userProfile:signup' %}>
            <img class="icon__mod icon__mod2" src={% static 'APP1/icon/signup.svg' %} alt="">
            Sign Up
          </a>
        </li>
        <li>
          <a style="display: flex;" data-target='dropdown2' href="{% url 'userProfile:login' %}">
            <img class="icon__mod icon__mod2" src={% static 'APP1/icon/login.svg' %} alt="">
            Login
          </a>
        </li>
      {% endif %}
    </ul>
  </section>

  <div id="clock" class="time hide-on-med-and-down">
    <i class="small material-icons">access_time</i>
    <span class="clock"></span>
  </div>
  <div class="body__container">
    {% block body %}


    {% endblock body %}
  </div>

  <footer style="text-align: center; padding: 10px;" class="page-footer">
    Made with ❤ by C07
  </footer>



  <!-- Compiled and minified JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function () {
      $('.sidenav').sidenav({
        edge: 'right',
        preventScrolling: 'false'
      });

      $('.tooltipped').tooltip({
        margin: -5,
        inDuration: 100,
        outDuration: 100,
        enterDelay: 0
      });
    })

    $('.dropdown-trigger').dropdown({
      closeOnClick: false,
      coverTrigger: false
    });

    if (window.innerWidth <= 992) {
      $('.logo__app').prop('src', '/static/APP1/icon/virus_tok.svg')
      $('.logo__app').css({
        'transform': 'scale(1.7) translateX(25%)'
      })
    }
  </script>
  <script type="text/javascript">
    function startTime() {
      var today = new Date();
      var h = today.getHours();
      var m = today.getMinutes();
      var s = today.getSeconds();
      m = checkTime(m);
      s = checkTime(s);
      $('.clock').html(h + ":" + m + ":" + s)
      setTimeout(startTime, 1000);
    }

    function checkTime(i) {
      if (i < 10) {
        i = "0" + i
      }; // add zero in front of numbers < 10
      return i;
    }
    startTime()
  </script>
  <script>
    var prevScrollpos = window.pageYOffset;
    window.onscroll = function() {
    var currentScrollPos = window.pageYOffset;
      if (prevScrollpos > currentScrollPos) {
        document.getElementById("clock").style.top = "64px";
      } else {
        document.getElementById("clock").style.top = "-50px";
      }
      prevScrollpos = currentScrollPos;
    }
  </script>
  {% block script %}

  {% endblock script %}

</body>

</html>

APP1/templates/APP1/landing.html
{% extends 'APP1/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href={% static 'APP1/landing.css' %}>
{% endblock head %}


{% block body %}
<div class="landing__app ">
  <div class="content__wrapper">
    <h4>
      Get in touch<br>
      with everything you<br>
      need to know!
    </h4>

    

    <div class="status__cov">
      <h5 style="
      font-size: 1.2rem; 
      font-weight: 500; 
      display: flex; 
      align-items: center; 
      margin: 10px auto; 
      width: fit-content;">
        <img style="display: inline; width: 30px; height: 20px; margin-right: 5px;" src="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.3/flags/4x3/id.svg" alt="">
        Indonesia
      </h5>
      <p>Recovered +<span id="incRecovery"></span></p>
      <div class="stat" id="recover">
        <img src={% static 'APP1/icon/recovery-white.svg' %} alt="">
        <p id="recovered"></p>
        
      </div>
      <p>Confirmed +<span id="incPositive"></span></p>
      <div class="stat" id="positif">
        <img src={% static 'APP1/icon/positive-white.svg' %} alt="">
        <p id="positive"></p>
        
      </div>
      <p>Deaths +<span id="incDeath"></span></p>
      <div class="stat" id="death">
        <img src={% static 'APP1/icon/dead-white.svg' %} alt="">
        <p id="deaths"></p>
        
      </div>
      
      <p>Last Updated:</p>
      <p id="last_updated"></p>
    </div>
  </div>
  <img class="corona__group" src={% static 'APP1/img/corona-group.png' %} alt="">
  <img class="corona__solo" src={% static 'APP1/img/corona-solo.png'%} alt="">
</div>

<div class="recent__post">
  <img class="corona__img" src={% static 'APP1/img/corona-post.png' %} alt="">
  <h4 class="recent__post__title">Recent News</h4>
  <div class="row">
    
    
    {% for news in list_news %}
      <div class="col s12 m6 l4">
      <div class="card medium hoverable">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src={{ news.image_url }}>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">{{ news.title|truncatechars:30 }}<i class="material-icons right">more_vert</i></span>
          <p><a href={% url 'news:news_detail' news.pk news.title|lower|slugify %}>Read more →</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">{{ news.title }}<i class="material-icons right">close</i></span>
          <p>{{ news.content|default:news.description }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
      
  </div>
</div>
{% endblock body %}


{% block script %}
<script type="text/javascript">
  function formatNumber(num) {
    return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,')
  }

  fetch('https://disease.sh/v3/covid-19/countries/IDN?strict=true')
    .then(response => response.json())
    .then(data => {
      let date = new Date(data.updated);
      let days = date.toLocaleString("id-ID", {weekday: "long"})
      let day = date.toLocaleString("id-ID", {day: "numeric"})
      let month = date.toLocaleString("id-ID", {month: "long"})
      let year = date.toLocaleString("id-ID", {year: "numeric"})
      $('#last_updated').html(`${days}, ${day} ${month} ${year}`)
      $('#deaths').html(formatNumber(data.deaths))
      $('#incDeath').html(formatNumber(data.todayDeaths))
      $('#positive').html(formatNumber(data.cases))
      $('#incPositive').html(formatNumber(data.todayCases))
      $('#recovered').html(formatNumber(data.recovered))
      $('#incRecovery').html(formatNumber(data.todayRecovered))
    })
</script>

{% endblock script %}

APP1/templates/APP1/search_result.html
{% extends 'APP1/base.html' %}
{% load static %}


{% block head %}
<link rel="stylesheet" href={% static 'news/news.css' %}>
{% endblock head %}


{% block body %}
<div class="news">
  <div class="container">
    <div class="row">

      {% if articles|length == 0 %}
        Hasil Pencarian tidak ditemukan
      {% else %}
      <p style="padding-top: 20px; padding-left: .75rem; font-size: 16px;" >
        Hasil pencarian 
        <b>"{{key}}"</b>
        , {{paginator.count}} hasil ditemukan
      </p>
      {% for artikel in articles %}

      <div class="col s12">
        <div class="card horizontal">
          <div class="card-image waves-effect waves-light">
            <a href={% url 'news:news_detail' artikel.pk artikel.title|lower|slugify %}>
              <img src={{artikel.image_url}}>
            </a>
          </div>
          <div class="card-stacked">
            <div class="card-content">
              <span class="card__badges">{{ artikel.name|default:"NaN" }}</span>
              <a href={% url 'news:news_detail' artikel.pk artikel.title|lower|slugify %}
                class="card-title">{{ artikel.title|truncatechars:80 }}</a>
              <p class="hide-on-med-and-down" style="margin-bottom: 15px;">{{ artikel.description|truncatechars:120 }}
              </p>
              <span>{{ artikel.timestamp|date:"l, j F Y" }}</span>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}

    </div>
  </div>


</div>


{% block pagination %}
  
  {% if articles|length != 0 %}

  <ul style="bottom: 0;
        position: absolute;
        transform: translate(-50%, 214%);
        left: 50%;
        text-align: center;" class="pagination">

  {% if articles.has_previous %}
  <li class="waves-effect"><a href="?search={{key}}&page={{articles.previous_page_number}}"><i
    class="material-icons">chevron_left</i></a></li>
    {% else %}
    <li class="disabled"><a><i class="material-icons">chevron_left</i></a></li>
    {% endif %}
    
    <li class="waves-effect">Page {{page|default:'1'}} of {{paginator.num_pages}}</li>
    
    {% if articles.has_next %}
    <li class="waves-effect"><a href="?search={{key}}&page={{articles.next_page_number}}"><i class="material-icons">chevron_right</i></a>
    </li>
    {% else %}
    <li class="disabled"><a><i class="material-icons">chevron_right</i></a></li>
    {% endif %}
    
  </ul>
  {% endif %}

{% endblock pagination %}

{% endblock body %}


{% block script %}

{% endblock script %}